# Generated by Django 3.2.5 on 2021-09-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210901_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_time'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AddField(
            model_name='article',
            name='content_text',
            field=models.TextField(default=123, max_length=10000, verbose_name='文章正文TEXT'),
            preserve_default=False,
        ),
    ]
